### ISSUE TITLE
[Feature Request] MALSync Integration

### ISSUE THREAD

**Issue by doccy-doc** [Animorphs/MAL-English-Titles#10]
There is a great extension available for most browsers called MALSync (https://malsync.moe/) that integrates MAL into popular streaming/manga sites and updates your MAL as you watch shows/read manga. The extension has a built in PWA quick-list (just a rendered web page accessible at https://malsync.moe/pwa) of your recent entries that is extremely useful to either open in MAL or continue watching on your streaming platform. 
Unfortunately, there is no option to force English titles in this list (I imagine due to MAL choosing not to). Would it be possible to include the PWA page in this script?

**Comment by Animorphs** [comment]
Thanks for the feature request.

I don't use MALsync so no promises, but is this along the lines of what you're thinking? 
<img src='https://i.imgur.com/h4Ydt7y.png'>
Unfortunately the space is a bit cramped with the longer titles.

Additionally, would it basically just be the https://malsync.moe/pwa/#/book/anime/1 and https://malsync.moe/pwa/#/book/manga/1 pages (including /2, /3 etc)?

**Comment by doccy-doc** [comment]
Yes! This is fine with me. I just have trouble remembering which title is which. This will be so handy if you can implement. Legend! 

.../book/anime/(1-9) each are for different statuses of the content, such as watching, planned, dropped, completed etc. so it would be best to have everything after .../book/ translated if possible.

**Comment by Animorphs** [comment]
So unfortunately it turns out it's not actually doable. 

MAL-sync is editable directly as an end user, which is what I did above in that screenshot, but the way it works is actually quite unusual. The https://malsync.moe/pwa website is actually just an iframe pointing to another website, with that "other website" being the extension itself. AKA it's not a normal website at all. This means that due to website/browser security, we encounter an issue with Cross-Origin Resource Sharing (CORS), which basically disables our ability to interact with the website at the level we need.

Whilst CORS can technically be disabled (which _might_ provide a workaround), I certainly do not recommend doing so due to the massive security hole that would create, so unfortunately this request will have to be denied due to technical limitations.
