### ISSUE TITLE
Why Use a Timeout?

### ISSUE THREAD

**Issue by nicegamer7** [Animorphs/MAL-English-Titles#4]
I just have a question regarding the script.

I noticed that translations show up two seconds after the page loads, and it's obviously because the main function is set to run after two seconds using a timeout. So my question is, why? I removed the timeout and the script continues to work fine. Albeit, I haven't tested every page.

I traced the change back to https://github.com/Animorphs/MAL-English-Titles/commit/af6c5dabe4d6e78364661da83ca2a44641e649df, so I assume it has something to do with the AJAX request that happens when your anime or manga list is too long. But unfortunately, I don't have a list long enough to test that.

**Comment by Animorphs** [comment]
I think the reason I added it was because sometimes it wouldn't load translations, so I thought it might be because of slow internet, but seems to be working fine when removed (as you said), even if I throttle my connection. I'll remove it now as it should make it a lot snappier, and if there's any side effects I can just chuck it back in. And shouldn't be related to the AJAX stuff, think that was just a coincidental simultaneous release.

Also if you wanted to check out a user with a super long list try [Valoon](https://myanimelist.net/profile/valoon), but fair warning the script will not like it, your computer may grind to a halt, and you will be timed out of MAL for a while.
